### ISSUE TITLE
How to set a global pseudo element styles?

### ISSUE THREAD

**Issue by cangSDARM** [JetBrains/kotlin-wrappers#527]
css:

```css
[draggable="true"] {
    user-select: none;
    -moz-user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
}
```

expect:

```kotlin
val styles = CSSBuilder().apply {
    apply("[draggable=\"true\"]") {   // I guess its name should be `apply`. but i dont know
       //css in there
    }
}

fun main() {
   styled.injectGlobal(styles.toString())
}
```

----

By the way, the interface mentioned in the section about global styles in the [document](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-styled/README.md) is wrong.
Not `StyledComponents`, should be `styled.injectGlobal` which exported from `kotlin-styled`
